# Aula 3 - NumPy e SciPy

A parte do numpy tem como principal base o guia oficial do usuário disponibilizado gratuitamente [aqui](https://docs.scipy.org/doc/numpy/numpy-user-1.16.1.pdf).

Observação: As notas a seguir estão em constante desenvolvimento, aperfeiçoamento e revisões.



<h1>Conteúdo<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Pré-requisitos" data-toc-modified-id="Pré-requisitos-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Pré-requisitos</a></span><ul class="toc-item"><li><span><a href="#Instalação-do-conda-(Miniconda)" data-toc-modified-id="Instalação-do-conda-(Miniconda)-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Instalação do conda (Miniconda)</a></span></li><li><span><a href="#Utilizando-e-instalando-ambientes-(envs)" data-toc-modified-id="Utilizando-e-instalando-ambientes-(envs)-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Utilizando e instalando ambientes (envs)</a></span></li></ul></li><li><span><a href="#A-biblioteca-NumPy" data-toc-modified-id="A-biblioteca-NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>A biblioteca NumPy</a></span><ul class="toc-item"><li><span><a href="#O-que-é?" data-toc-modified-id="O-que-é?-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>O que é?</a></span></li><li><span><a href="#Conceitos-básicos" data-toc-modified-id="Conceitos-básicos-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Conceitos básicos</a></span><ul class="toc-item"><li><span><a href="#Importando-o-pacote" data-toc-modified-id="Importando-o-pacote-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Importando o pacote</a></span></li><li><span><a href="#Tipo-básico:-numpy.ndarray" data-toc-modified-id="Tipo-básico:-numpy.ndarray-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Tipo básico: <code>numpy.ndarray</code></a></span><ul class="toc-item"><li><span><a href="#Inicializando" data-toc-modified-id="Inicializando-2.2.2.1"><span class="toc-item-num">2.2.2.1&nbsp;&nbsp;</span>Inicializando</a></span></li><li><span><a href="#Inicializando-arrays-preenchidos-com-zeros-ou-um" data-toc-modified-id="Inicializando-arrays-preenchidos-com-zeros-ou-um-2.2.2.2"><span class="toc-item-num">2.2.2.2&nbsp;&nbsp;</span>Inicializando arrays preenchidos com zeros ou um</a></span></li><li><span><a href="#Atributos-básicos" data-toc-modified-id="Atributos-básicos-2.2.2.3"><span class="toc-item-num">2.2.2.3&nbsp;&nbsp;</span>Atributos básicos</a></span></li></ul></li></ul></li><li><span><a href="#Operações-e-utilitários-básicos" data-toc-modified-id="Operações-e-utilitários-básicos-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Operações e utilitários básicos</a></span><ul class="toc-item"><li><span><a href="#Criação-de-arrays-a-partir-de-intervalos:" data-toc-modified-id="Criação-de-arrays-a-partir-de-intervalos:-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>Criação de arrays a partir de intervalos:</a></span></li><li><span><a href="#Operações-aritméticas" data-toc-modified-id="Operações-aritméticas-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>Operações aritméticas</a></span></li><li><span><a href="#Comentários-sobre-operações-com-tipos-de-dados-distintos" data-toc-modified-id="Comentários-sobre-operações-com-tipos-de-dados-distintos-2.3.3"><span class="toc-item-num">2.3.3&nbsp;&nbsp;</span>Comentários sobre operações com tipos de dados distintos</a></span></li></ul></li><li><span><a href="#Funções-universais-da-NumPy" data-toc-modified-id="Funções-universais-da-NumPy-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Funções universais da NumPy</a></span></li><li><span><a href="#Alguns-métodos-de-numpy.ndarray-úteis" data-toc-modified-id="Alguns-métodos-de-numpy.ndarray-úteis-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Alguns métodos de <code>numpy.ndarray</code> úteis</a></span><ul class="toc-item"><li><span><a href="#Valores-máximos-e-mínimos-em-um-array" data-toc-modified-id="Valores-máximos-e-mínimos-em-um-array-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>Valores máximos e mínimos em um array</a></span></li><li><span><a href="#Somas-e-produtos-dos-valores-em-um-array" data-toc-modified-id="Somas-e-produtos-dos-valores-em-um-array-2.5.2"><span class="toc-item-num">2.5.2&nbsp;&nbsp;</span>Somas e produtos dos valores em um array</a></span></li><li><span><a href="#E-o-que-acontece-em-arrays-multidimensionais?" data-toc-modified-id="E-o-que-acontece-em-arrays-multidimensionais?-2.5.3"><span class="toc-item-num">2.5.3&nbsp;&nbsp;</span>E o que acontece em arrays multidimensionais?</a></span></li></ul></li><li><span><a href="#Indexação,-fatiamento-e-iterações-em-arrays" data-toc-modified-id="Indexação,-fatiamento-e-iterações-em-arrays-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Indexação, fatiamento e iterações em arrays</a></span><ul class="toc-item"><li><span><a href="#Indexação" data-toc-modified-id="Indexação-2.6.1"><span class="toc-item-num">2.6.1&nbsp;&nbsp;</span>Indexação</a></span></li><li><span><a href="#Fatiamento" data-toc-modified-id="Fatiamento-2.6.2"><span class="toc-item-num">2.6.2&nbsp;&nbsp;</span>Fatiamento</a></span><ul class="toc-item"><li><span><a href="#Array-unidimensional" data-toc-modified-id="Array-unidimensional-2.6.2.1"><span class="toc-item-num">2.6.2.1&nbsp;&nbsp;</span>Array unidimensional</a></span></li><li><span><a href="#Array-multidimensional" data-toc-modified-id="Array-multidimensional-2.6.2.2"><span class="toc-item-num">2.6.2.2&nbsp;&nbsp;</span>Array multidimensional</a></span></li></ul></li><li><span><a href="#Iterações" data-toc-modified-id="Iterações-2.6.3"><span class="toc-item-num">2.6.3&nbsp;&nbsp;</span>Iterações</a></span></li></ul></li><li><span><a href="#Manipulação-de-shapes" data-toc-modified-id="Manipulação-de-shapes-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Manipulação de shapes</a></span></li><li><span><a href="#Empilhamento-de-arrays" data-toc-modified-id="Empilhamento-de-arrays-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Empilhamento de arrays</a></span></li><li><span><a href="#Cópias-e-visões-de-arrays" data-toc-modified-id="Cópias-e-visões-de-arrays-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>Cópias e visões de arrays</a></span><ul class="toc-item"><li><span><a href="#Sem-cópias" data-toc-modified-id="Sem-cópias-2.9.1"><span class="toc-item-num">2.9.1&nbsp;&nbsp;</span>Sem cópias</a></span></li><li><span><a href="#Visão-ou-cópia-raza-(shallow-copy)" data-toc-modified-id="Visão-ou-cópia-raza-(shallow-copy)-2.9.2"><span class="toc-item-num">2.9.2&nbsp;&nbsp;</span>Visão ou cópia raza (shallow copy)</a></span></li><li><span><a href="#Cópia-profunda-(deep-copy)" data-toc-modified-id="Cópia-profunda-(deep-copy)-2.9.3"><span class="toc-item-num">2.9.3&nbsp;&nbsp;</span>Cópia profunda (deep copy)</a></span></li></ul></li></ul></li></ul></div>

## Pré-requisitos

Podemos explorar nossos estudos desse ponto em diante de duas formas:

* Localmente com Jupyter Notebooks;
* Remotamente com o [Google Colab](https://colab.research.google.com).

Este último já vem previamente configurado com todas as libs que utilizaremos na parte numérica do curso. Para a primeira opção, para que tudo corra bem, precisamos garantir que todo mundo está utilizando a mesma versão tanto do Python quanto em suas libs. Para isso, vamos utilizar o [conda](https://conda.io/en/latest/), um gerenciador open source de pacotes e ambientes.

### Instalação do conda (Miniconda)

Caso sua máquina não possua o conda instalado, você pode baixar o instalador condizente com seu computador e sistema operacional [neste link](https://conda.io/en/latest/miniconda.html), basta seguir as instruções lá providenciadas. Com isso, você instalará o Miniconda - a versão com "o mínimo necessário" do conda - em seu computador, que é o que iremos precisar aqui.

### Utilizando e instalando ambientes (envs)

Após instalado o `conda` e reiniciado seu terminal, você deve ser capaz de checar os ambientes (environments, que chamaremos apenas de envs) instalados (execute o comando abaixo sem `!` no seu terminal):

In [201]:
!conda env list

# conda environments:
#
base                     /home/volps/miniconda3
daml                     /home/volps/miniconda3/envs/daml
fenics16-1               /home/volps/miniconda3/envs/fenics16-1
fenics16-2               /home/volps/miniconda3/envs/fenics16-2
fenics17-1               /home/volps/miniconda3/envs/fenics17-1
fenics17-2               /home/volps/miniconda3/envs/fenics17-2
fenics18-1               /home/volps/miniconda3/envs/fenics18-1
sci                      /home/volps/miniconda3/envs/sci
sci_env               *  /home/volps/miniconda3/envs/sci_env



Este comando lista os envs instalados. Note que já temos um env que você provavelmente ainda não tem (a menos que vc esteja executando este notebook no Colab). Vamos resolver isso?

Para tanto, siga a sequência de passos abaixo:

1. Clone o repositório remoto do curso para sua máquina com o comando `git clone https://github.com/pedrosiracusa/curso_python_eamc.git` e entre no diretório com `cd curso_python_eamc`

2. Adicione o canal (`conda-forge`) que utilizaremos para baixar os pacotes corretos no conda: `conda config --add channels conda-forge`

3. Crie o mesmo pacote que temos - o `sci_env` - por meio do arquivo de dependências `sci_env.yml` com o seguinte comando: `conda env create -f sci_env.yml`

4. Aguarde a instala...zzzzZZZZZZZZZZZZZZZZzzZZZzz

5. Após a instalação, reinicie seu terminal e acesse o ambiente com o comando `source activate sci_env` (Linux) ou `conda activate sci_env` (Windows).

Pronto, com isso temos exatamente o mesmo ambiente, com as mesmas bibliotecas!

## A biblioteca NumPy

### O que é?

É um pacote fundamental para aplicações de computação científica em Python. Com ele, o desenvolvedor é capaz de:

* Montar objetos matriciais N-dimensionais e objetos derivados desses;
* Realizar operações eficientes de Álgebra Linear computacional;
* Operações básicas de Estatística;
* Utilizar geração de números pseudo-aleatórios;
* Operações vetorizadas;
* Integrar com códigos em C/C++ e Fortran;

E muito mais!

### Conceitos básicos

#### Importando o pacote

In [202]:
import numpy as np

#### Tipo básico: `numpy.ndarray`

O tipo básico da `numpy` é o `numpy.ndarray`, o quão chamaremos aqui frequentemente de "array".

##### Inicializando

Um simples vetor:

In [203]:
array1 = np.array([1., 2., 3.])

array1

array([1., 2., 3.])

Uma matriz:

In [204]:
matrix1 = np.array(
    [[1., 2., 3.],
     [4., 5., 6.],
     [7., 8., 9.]]
)

matrix1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Note que a matriz nada mais é que um array de arrays.

Ao longo do curso, veremos outras formas de inicializar arrays.

**Atenção!!!**

A entrada para a criação de arrays deve ser listas ou tuplas:

In [205]:
array_tuple = np.array((1, 2, 3))

array_tuple

array([1, 2, 3])

In [206]:
matrix_mixed = np.array(
    [(1, 2, 3),
    [4, 5, 6]]
)

matrix_mixed

array([[1, 2, 3],
       [4, 5, 6]])

##### Inicializando arrays preenchidos com zeros ou um

Em algumas situações, já são conhecidas as demandas e estruturas dos arrays que vão ser utilizados. Neste caso, o numpy oferece funções para criar arrays preenchidos com zeros ou um.

* Vetor

In [207]:
array_zeros = np.zeros(3)
array_zeros

array([0., 0., 0.])

* Matriz

In [208]:
shape = (4, 4)
matrix_zeros = np.zeros(shape)
matrix_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Analogamente, podemos fazer com valor unitário.

* Vetor

In [209]:
array_ones = np.ones(3)
array_ones

array([1., 1., 1.])

* Matriz

In [210]:
shape = (4, 4)
matrix_ones = np.ones(shape)
matrix_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##### Atributos básicos

* Número de eixos (axes) do array:

In [211]:
array1.ndim

1

In [212]:
matrix1.ndim

2

Note que uma matriz, nesse caso, é considerado um objeto bidimensional, já que são arrays dentro de um array.

* Forma de um array:

In [213]:
array1.shape

(3,)

In [214]:
matrix1.shape

(3, 3)

`ndarray.shape` fornece as dimensões de cada eixo. No caso de uma matriz $A \in \mathbb{R}^{m\,\times\,n}$, como temos em `matrix1`, `ndarray.shape` retorna justamente $(m, n)$.

* Tamanho de um array:

In [215]:
array1.size

3

In [216]:
matrix1.size

9

Retorna o número de entrada de valores no objeto `ndarray`.

* Tipo dos elementos em um array:

In [217]:
array1.dtype

dtype('float64')

In [218]:
matrix1.dtype

dtype('float64')

Ou seja, todas as entradas foram compostas por números em representação de ponto flutuante de dupla precisão. Caso seja necessário utilizar outro tipo de representação, podemos especificar isso na hora de declaramos o array por meio do argumento `dtype`:

In [219]:
matrix1_32 = np.array(
    [[1., 2., 3.],
     [4., 5., 6.],
     [7., 8., 9.]],
    dtype=np.float32
)

In [220]:
matrix1_32.dtype

dtype('float32')

Ou mesmo podemos criar arrays de números complexos:

In [221]:
array_complex = np.array([[2. + 3.j, 1.]], dtype=np.complex)

array_complex

array([[2.+3.j, 1.+0.j]])

In [222]:
matrix_complex = np.array(
    [[2. + 1.j, 1.],
     [0., 1.j]], 
    dtype=np.complex
)

matrix_complex

array([[2.+1.j, 1.+0.j],
       [0.+0.j, 0.+1.j]])

* Tamanhos dos itens em bytes de um array:

In [223]:
array1.itemsize

8

In [224]:
matrix1.itemsize

8

In [225]:
matrix1_32.itemsize

4

Note que um array de `float64` tem $\dfrac{64}{8} = 8$ bytes, enquanto um `float32` tem $\dfrac{32}{8} = 4$ bytes.

* Endereço dos dados em memória:

In [226]:
array1.data

In [227]:
matrix1.data

In [228]:
matrix1_32.data

Em Python, geralmente não utilizamos esse tipo de acesso ou informação. Utilizamos apenas a **_parte boa_** do C.

### Operações e utilitários básicos

#### Criação de arrays a partir de intervalos:

In [229]:
sequence_1 = np.arange(start=2, stop=10, step=2)

sequence_1

array([2, 4, 6, 8])

ou

In [230]:
sequence_2 = np.linspace(start=2, stop=8, num=4)

sequence_2

array([2., 4., 6., 8.])

Note que embora ambos criem arrays igualmente espaçados, exite uma diferença na forma de uso. O `np.arange` te possibilita dizer o início e o fim, sendo que o fim não está incluso (assim como ocorre com os _slicing_ de listas). Além disso, o `np.arange` controla o incremento que será utilizado até alcançar o fim da sequência.

Em contrapartida, o `np.linspace` controla precisamente o início e o fim (que estará incluso). No entanto, ele tem como entrada no terceiro argumento (aqui explicitado) a quantidade de pontos que terá entre o início e o fim. O incremento será consequência disso.

Para simplificar, geralmente ambos os métodos são usados com o nome dos argumentos implícitos:

In [231]:
sequence_1 = np.arange(2, 10, 2)

sequence_1

array([2, 4, 6, 8])

In [232]:
sequence_2 = np.linspace(2, 8, 4)

sequence_2

array([2., 4., 6., 8.])

In [233]:
sequence_3 = np.linspace(0, 100, 200)

sequence_3

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

#### Operações aritméticas

Com o numpy, as operações aritméticas são realizadas elemento-por-elemento do array.

In [234]:
a = np.arange(5)

a

array([0, 1, 2, 3, 4])

(note que se `np.arange` tiver apenas um argumento, ele gerará uma sequência igualmente espaçada até o número inteiro imediatamente antes ao argumento)

In [235]:
b = np.arange(0, 50, 10)

b

array([ 0, 10, 20, 30, 40])

In [236]:
soma = a + b
subtracao = b - a
potenciacao = a ** 2
divisao = b[1:] / a[1:]
produto = a * b

print(soma)
print(subtracao)
print(potenciacao)
print(divisao)
print(produto)

[ 0 11 22 33 44]
[ 0  9 18 27 36]
[ 0  1  4  9 16]
[10. 10. 10. 10.]
[  0  10  40  90 160]


Note que a operação de divisão de vetores não é matematicamente definida, mas aqui é possível pois se trata de operações elemento-por-elemento. Além disso, o produto entre vetores matematicamente definido como produto interno não ocorre por meio do operador `*` (iremos ver isso em breve). Podemos fazer com matrizes de maneira similar:

In [237]:
A = np.array(
    [[1., 3.], 
     [2., 4.]]
)
B = np.array(
    [[10., 0.], 
     [10., 20.]]
)

print(A, '\n')
print(B)

[[1. 3.]
 [2. 4.]] 

[[10.  0.]
 [10. 20.]]


In [238]:
soma = A + B
subtracao = B - A
potenciacao = A ** 2
divisao = B / A
produto = A * B

print(soma, '\n')
print(subtracao, '\n')
print(potenciacao, '\n')
print(divisao, '\n')
print(produto)

[[11.  3.]
 [12. 24.]] 

[[ 9. -3.]
 [ 8. 16.]] 

[[ 1.  9.]
 [ 4. 16.]] 

[[10.  0.]
 [ 5.  5.]] 

[[10.  0.]
 [20. 80.]]


Novamente, note que a operação de divisão em matrizes matematicamente não existe e o produto entre matrizes também não é o usual. As operações que ocorrem acima foram realizadas elemento-por-elemento. Caso desejemos realizar o produto de matrizes, o Python oferece um operador específico para isso:

In [239]:
produto_matrizes = A @ B

produto_matrizes

array([[40., 60.],
       [60., 80.]])

ou

In [240]:
produto_matrizes_alternativo = A.dot(B)

produto_matrizes_alternativo

array([[40., 60.],
       [60., 80.]])

sendo esse último uma notação mais verbosa do que está ocorrendo. Podemos, dessa forma, fazer a clássica operação entre matrizes e vetores do tipo $Ax$:

In [241]:
mat = np.array([[2., 1.], [1, 2.]])
vec = np.array([1., 0.])
prod_matvec = mat @ vec

prod_matvec

array([2., 1.])

#### Comentários sobre operações com tipos de dados distintos

Quando se opera objetos `ndarray` com tipos diferentes, o que será que acontece?

In [242]:
a = np.ones(3, dtype=np.int32)

a

array([1, 1, 1], dtype=int32)

In [243]:
b = np.linspace(0, 5, 3)

b

array([0. , 2.5, 5. ])

In [244]:
a + b

array([1. , 3.5, 6. ])

Note que ocorre uma coerção de tipo para o que apresentar maior grau de precisão (ou mais genérico).

### Funções universais da NumPy

A NumPy fornece as principais funções matemáticas capazes de operar de forma vetorial. Em outras palavras, capaz de retornar arrays, ao contrário da biblioteca-padrão `math`. Vamos ver um exemplo simples:

In [245]:
import math


def sin_function(x):
    return math.sin(x)

In [246]:
vec = np.array([1 / 3, 1 / 2])
sin_vec = sin_function(vec)

sin_vec

TypeError: only size-1 arrays can be converted to Python scalars

Pela numpy:

In [247]:
def sin_function_np(x):
    return np.sin(x)

In [248]:
sin_vec = sin_function_np(vec)

sin_vec

array([0.3271947 , 0.47942554])

Basicamente, as funções fornecidas são as mesmas que as da lib `math`, porém com a capacidade exibida acima. Lembrando que essas funções também são executadas elemento-por-elemento. A lista completa de funções disponíveis pode ser acessada [aqui](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html).

### Alguns métodos de `numpy.ndarray` úteis

No dia-a-dia científico, muitas vezes necessitamos de algumas operações com certa frequência, como somas em vetores, valores máximos ou mínimos e etc. Os objetos `ndarray` são munidos de métodos que executam esses cálculos. Vejamos alguns deles a seguir.

#### Valores máximos e mínimos em um array

Vamos antes gerar um vetor de valores aleatórios com o pacote `random` do numpy:

In [249]:
from numpy import random as rnd

array1 = rnd.random(10)

array1

array([0.19674247, 0.13274832, 0.85797634, 0.14331389, 0.87662083,
       0.51507581, 0.76077558, 0.49681619, 0.87649872, 0.4878207 ])

Criamos um vetor com 10 entradas aleatórias entre 0 e 1. Agora vamos retirar algumas informações sobre ele.

* Valor máximo

In [250]:
array1.max()

0.876620829357751

* Índice da entrada de valor máximo

In [251]:
imax = array1.argmax()
imax

4

In [252]:
array1[imax]

0.876620829357751

* Valor mínimo

In [253]:
array1.min()

0.1327483192710749

* Índice da entrada de valor mínimo

In [254]:
array1.argmin()

1

#### Somas e produtos dos valores em um array

* Soma dos valores

In [255]:
array1.sum()

5.344388853791151

* Soma cumulativa

In [256]:
array1.cumsum()

array([0.19674247, 0.32949079, 1.18746713, 1.33078102, 2.20740185,
       2.72247766, 3.48325324, 3.98006943, 4.85656816, 5.34438885])

Note que:

In [257]:
array1.sum() == array1.cumsum()[-1]

False

* Produto dos valores

In [258]:
array1.prod()

0.00023433518634952802

* Produto cumulativo dos valores

In [259]:
array1.cumprod()

array([0.19674247, 0.02611723, 0.02240797, 0.00321137, 0.00281516,
       0.00145002, 0.00110314, 0.00054806, 0.00048037, 0.00023434])

Também é constatado que:

In [260]:
array1.prod() == array1.cumprod()[-1]

True

#### E o que acontece em arrays multidimensionais?

Neste caso, o formato não é levado em conta. O método é aplicado ao longo do array como se os valores de entradas fossem uma lista.

In [261]:
shape = (3, 3)
vec1 = rnd.random(shape)

vec1

array([[0.78476469, 0.81667054, 0.60793283],
       [0.37237763, 0.32278825, 0.38206478],
       [0.39163892, 0.48519594, 0.43236465]])

In [262]:
vec1.min()

0.32278825135901457

Porém, podemos especificar em qual `axis` os métodos serão aplicados:

In [263]:
vec1.min(axis=1)

array([0.60793283, 0.32278825, 0.39163892])

A operação acima retornou o mínimo de cada linha. Analogamente:

In [264]:
vec1.min(axis=0)

array([0.37237763, 0.32278825, 0.38206478])

retornou o mínimo em cada coluna. O procedimento pode ser aplicado da mesma maneira para as funções expostas anteriormente.

### Indexação, fatiamento e iterações em arrays

#### Indexação

In [265]:
array1 = np.linspace(5, 20, 10)
array1

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ])

Semelhantemente às listas, os índices começam a contar do 0. Portanto, a entrada na posição 3 é acessado como

In [266]:
array1[2]

8.333333333333334

#### Fatiamento

##### Array unidimensional

Em algumas situações, se deseja acessar ou operar em apenas uma parte de um array. No array unidimensional, basta fazer `array[n:m]`. Isso retornará as entradas do índice `n` até o `m-1`.

In [267]:
array1[0:3]

array([5.        , 6.66666667, 8.33333333])

Neste caso, como o índice inicial é `0`, podemos omitir e simplesmente fazer

In [268]:
array1[:3]

array([5.        , 6.66666667, 8.33333333])

De forma semelhante, se fizermos `array[n:]` a fatia ocorrerá do índice `n` até o fim do array:

In [269]:
array1[7:]

array([16.66666667, 18.33333333, 20.        ])

Outro exemplo:

In [270]:
sliced_array = array1[2:8]
sliced_array

array([ 8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ,
       16.66666667])

Também podemos fazer operações em apenas trechos dos arrays:

In [271]:
array1[:3] + 10

array([15.        , 16.66666667, 18.33333333])

Ou operar partes de arrays com outras partes de outras arrays **(sem fazer laços!)**, desde que sejam compatíveis em tamanho e dimensões:

In [272]:
array2 = np.linspace(0, 5, 10)
array3 = array1[:5] + array2[5:]

array3

array([ 7.77777778, 10.        , 12.22222222, 14.44444444, 16.66666667])

Esse tipo de operação entre arrays, sem laços, é conhecida como uma das coisas mais poderosas da NumPy, e é comumente chamado de vetorização. Vejamos que alguns exemplos de performance:

In [273]:
array1, array2 = rnd.random(1000), rnd.random(1000)

In [274]:
%%timeit
n = 800
array3 = np.zeros(n)
for i in range(n):
    array3[i] = array1[i] + array2[i]
    
array3

344 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [275]:
%%timeit
array3 = array1[:n] + array2[:n]

array3

948 ns ± 13.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Então podemos verificar que há um ganho de performance/complexidade temporal na ordem de 300 com a operação vetorizada.

##### Array multidimensional

Neste caso, o fatiamento é aplicado em cada eixo (`axis`) separadamente.

In [276]:
shape = (4, 4)
matrix1 = rnd.randint(5, size=shape)

print(matrix1)

[[3 1 4 3]
 [3 1 2 1]
 [2 3 2 1]
 [0 4 4 1]]


* Todas as linhas (`:`) da coluna 2:

In [277]:
matrix1[:, 1]

array([1, 1, 3, 4])

* Todas as colunas da linha 4:

In [278]:
matrix1[3, :]

array([0, 4, 4, 1])

* Uma matriz formada das linhas 1 até 3 e com as colunas de 2 e 3 `matrix1`:

In [279]:
matrix2 = matrix1[:3, 1:3]

matrix2

array([[1, 4],
       [1, 2],
       [3, 2]])

Agora vamos fazer também um comparativo de performance.

In [280]:
shape = (200, 200)
matrix1 = rnd.randint(5, size=shape)
matrix2 = rnd.randint(5, size=shape)
matrix3_loop = np.zeros(shape)

In [281]:
%%timeit
for j in range(matrix1.shape[0]):
    for i in range(matrix1.shape[1]):
        matrix3_loop[i, j] = matrix1[i, j] + matrix2[i, j]

21.5 ms ± 466 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [282]:
%%timeit
matrix3[:, :] = matrix1[:, :] + matrix2[:, :]

42.1 µs ± 296 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Apenas fazendo um simples teste de sanidade:

In [283]:
np.array_equal(matrix3, matrix3_loop)

True

Disso, vemos que as operações foram equivalentes, porém a forma vetorizada teve um ganho em performance/complexidade temporal praticamente de $\mathcal{O}(10^3)$.

#### Iterações

De forma análoga às listas em Python, podemos iterar sobre objetos `numpy.ndarray`.

In [284]:
matrix1 = rnd.randint(10, size=(3, 3))
matrix1

array([[8, 5, 4],
       [6, 1, 0],
       [7, 8, 7]])

In [285]:
for row in matrix1:
    print(row)

[8 5 4]
[6 1 0]
[7 8 7]


Também é válido para percorrer elementos em vetores (arrays unidimensionais):

In [286]:
array1 = rnd.randint(5, size=5)
array1

array([4, 2, 2, 0, 4])

In [287]:
for element in array1:
    print(element)

4
2
2
0
4


### Manipulação de shapes

Em situações práticas, pode ser que seja necessário um rearranjo da configuração de um array. Aqui veremos brevemente como podemos mudar os shapes dos arrays.

In [288]:
shape = (3, 4)
matrix1 = rnd.randint(10, size=shape)

matrix1

array([[1, 5, 6, 7],
       [2, 4, 5, 1],
       [3, 7, 1, 2]])

In [289]:
matrix1.shape

(3, 4)

Como já vimos, o atributo `shape` nos informa quantos elementos há em cada eixo do array multidimensional. Inicialmente, vamos transformar a `matrix1` em um array unidimensional:

In [290]:
matrix1.ravel()

array([1, 5, 6, 7, 2, 4, 5, 1, 3, 7, 1, 2])

Podemos também rearranjar o conteúdo de um array para um outro shape:

In [291]:
new_shape = (2, 6)
matrix1.reshape(new_shape)

array([[1, 5, 6, 7, 2, 4],
       [5, 1, 3, 7, 1, 2]])

Note que é necessário que `shape[0] * shape[1] = new_shape[0] * new_shape[1]`. Mais precisamente, o tamanho do array rearranjado deve ser igual ao do array original. Veja o erro abaixo:

In [292]:
new_shape = (3, 3)
matrix1.reshape(new_shape)

ValueError: cannot reshape array of size 12 into shape (3,3)

É importante observar que o `reshape` não altera o array original, apenas devolve um array rearranjado em relação ao original:

In [293]:
matrix1

array([[1, 5, 6, 7],
       [2, 4, 5, 1],
       [3, 7, 1, 2]])

Portanto, `matrix1` se mantém inalterada. Isso não ocorre quando se utiliza o `resize`, que modifica também o array original:

In [294]:
new_shape = (2, 6)
matrix1.resize(new_shape)

matrix1

array([[1, 5, 6, 7, 2, 4],
       [5, 1, 3, 7, 1, 2]])

### Empilhamento de arrays

Digamos que precisamos unir os dados presentes em dois arrays diferentes. Aqui veremos sucintamente algumas maneiras de fazer isso.

In [295]:
shape = (2, 2)
matrix1, matrix2 = rnd.randint(5, size=shape), rnd.randint(4, size=shape)

print(matrix1, '\n')
print(matrix2)

[[4 3]
 [0 0]] 

[[3 3]
 [1 3]]


* Empilhamento horizontal

Os arrays são concatenados horizontalmente:

In [296]:
np.hstack([matrix1, matrix2])

array([[4, 3, 3, 3],
       [0, 0, 1, 3]])

* Empilhamento vertical

Analogamente:

In [297]:
np.vstack([matrix1, matrix2])

array([[4, 3],
       [0, 0],
       [3, 3],
       [1, 3]])

* Empilhamento de um vetor como coluna em uma matriz

In [298]:
array1 = np.array([10., 10.])

np.hstack([matrix1, array1])

ValueError: all the input arrays must have same number of dimensions

Observe que isso não é possível com o `hstack`. Porém, temos o `column_stack` para nos salvar!

In [299]:
np.column_stack([matrix1, array1])

array([[ 4.,  3., 10.],
       [ 0.,  0., 10.]])

Também podemos utilizar o `column_stack` para montar um array multidimensional a partir de arrays que irão compor as colunas:

In [300]:
array2 = np.array([15, 30])

np.column_stack([array1, array2])

array([[10., 15.],
       [10., 30.]])

Analogamente, podemos concatenar como linhas:

In [301]:
np.row_stack([array1, array2])

array([[10., 10.],
       [15., 30.]])

Em tempo, podemos adicionar dois arrays com a função `append`, que difere um pouco do seu primo nos objetos `list`:

In [302]:
np.append(array1, array2)

array([10., 10., 15., 30.])

Isso também pode ser usado no numpy para criar arrays "dinamicamente" (que não existe no numpy, exatamente):

In [303]:
an_array = np.array([])  # cria um array vazio
for i in range(10):
    an_array = np.append(an_array, i)
    
an_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

A grosso modo, a função `append` possui a seguinte sintaxe: `np.append(array, value)`, onde `array` será adicionado por `value`, que pode ser também um outro `ndarray` ou tipos compatíveis, como `list` ou `tuple`. O `append` não modifica o `array`, retorna um novo `ndarray` com operado como requerido na chamada da função.

**Observação:** Criar arrays com `append` pode ser custoso! Afinal, usa laços em Python.

### Cópias e visões de arrays

Durante criação e manipulações de arrays, às vezes cópias são realizadas ou às vezes temos apenas visões dos arrays. Com numpy, temos alguns tipos de cópias e isso pode ser crucial quando desejamos manipular dados apropriadamente ou mantê-los intactos. Basicamente, temos apenas três casos e os veremos a seguir.

#### Sem cópias

Em geral, declarações não fazem cópias dos arrays.

In [304]:
array1 = np.arange(0, 10, 2)

array1

array([0, 2, 4, 6, 8])

In [305]:
array2 = array1

array1 is array2

True

Então os arrays são iguais. Em Python, isso quer dizer que um mesmo objeto possui dois nomes (ou mais). O que acontece se um dos arrays for modificado?

In [306]:
array2[-1] = 10

array1

array([ 0,  2,  4,  6, 10])

É importante ter **muita atenção** nisso, pois é uma fonte de bugs frequente. Funções em Python também modificam o valor dos argumentos:

In [307]:
def f_bug(x):
    x[0] = 20.0
    print(x)

In [308]:
f_bug(array1)

[20  2  4  6 10]


In [309]:
array1

array([20,  2,  4,  6, 10])

Isso é conhecido como **passagem por referência** de um argumento de uma função.

#### Visão ou cópia raza (shallow copy)

Neste caso, diferentes objetos compartilham os mesmos dados. O método `view` cria um novo array com dados iguais aos de outro array.

In [310]:
array2 = array1.view()

array2

array([20,  2,  4,  6, 10])

In [311]:
array2 is array1

False

In [312]:
array2.base is array1

True

O que acontece com o `array1` se modificarmos o `array2`?

In [313]:
array2 = array2 + 5

array1

array([20,  2,  4,  6, 10])

Aparentemente tudo OK! Esse tipo de cópia ocorre nos fatiamentos, onde são geradas as "visões" dos dados para um novo array:

In [314]:
array3 = array1[1:4]

array3

array([2, 4, 6])

In [315]:
array3[1] = 40

array1

array([20,  2, 40,  6, 10])

Então também devemos tomar cuidado com isso!

#### Cópia profunda (deep copy)

É uma perfeita cópia, totalmente independente dos dados originais (e segura!). É feita por meio do método `copy()`.

In [316]:
array3 = array1.copy()

In [317]:
array3 is array1

False

In [318]:
array3.base is array1

False

In [319]:
array3[:3] = 0.0

array1

array([20,  2, 40,  6, 10])

E assim estamos totalmente a salvos!