# Aula 3 - NumPy e SciPy

A parte do numpy tem como principal base o guia oficial do usuário disponibilizado gratuitamente [aqui](https://docs.scipy.org/doc/numpy/numpy-user-1.16.1.pdf)

Observação: As notas a seguir estão em constante desenvolvimento, aperfeiçoamento e revisões.

<h1>Conteúdo<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Pré-requisitos" data-toc-modified-id="Pré-requisitos-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Pré-requisitos</a></span><ul class="toc-item"><li><span><a href="#Instalação-do-conda-(Miniconda)" data-toc-modified-id="Instalação-do-conda-(Miniconda)-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Instalação do conda (Miniconda)</a></span></li><li><span><a href="#Utilizando-e-instalando-ambientes-(envs)" data-toc-modified-id="Utilizando-e-instalando-ambientes-(envs)-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Utilizando e instalando ambientes (envs)</a></span></li></ul></li><li><span><a href="#A-biblioteca-NumPy" data-toc-modified-id="A-biblioteca-NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>A biblioteca NumPy</a></span><ul class="toc-item"><li><span><a href="#O-que-é?" data-toc-modified-id="O-que-é?-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>O que é?</a></span></li><li><span><a href="#Conceitos-básicos" data-toc-modified-id="Conceitos-básicos-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Conceitos básicos</a></span><ul class="toc-item"><li><span><a href="#Importando-o-pacote" data-toc-modified-id="Importando-o-pacote-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Importando o pacote</a></span></li><li><span><a href="#Tipo-básico:-numpy.ndarray" data-toc-modified-id="Tipo-básico:-numpy.ndarray-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Tipo básico: <code>numpy.ndarray</code></a></span><ul class="toc-item"><li><span><a href="#Inicializando" data-toc-modified-id="Inicializando-2.2.2.1"><span class="toc-item-num">2.2.2.1&nbsp;&nbsp;</span>Inicializando</a></span></li><li><span><a href="#Inicializando-arrays-preenchidos-com-zeros-ou-um" data-toc-modified-id="Inicializando-arrays-preenchidos-com-zeros-ou-um-2.2.2.2"><span class="toc-item-num">2.2.2.2&nbsp;&nbsp;</span>Inicializando arrays preenchidos com zeros ou um</a></span></li><li><span><a href="#Atributos-básicos" data-toc-modified-id="Atributos-básicos-2.2.2.3"><span class="toc-item-num">2.2.2.3&nbsp;&nbsp;</span>Atributos básicos</a></span></li></ul></li></ul></li><li><span><a href="#Operações-e-utilitários-básicos" data-toc-modified-id="Operações-e-utilitários-básicos-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Operações e utilitários básicos</a></span><ul class="toc-item"><li><span><a href="#Criação-de-arrays-a-partir-de-intervalos:" data-toc-modified-id="Criação-de-arrays-a-partir-de-intervalos:-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>Criação de arrays a partir de intervalos:</a></span></li><li><span><a href="#Operações-aritméticas" data-toc-modified-id="Operações-aritméticas-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>Operações aritméticas</a></span></li><li><span><a href="#Comentários-sobre-operações-com-tipos-de-dados-distintos" data-toc-modified-id="Comentários-sobre-operações-com-tipos-de-dados-distintos-2.3.3"><span class="toc-item-num">2.3.3&nbsp;&nbsp;</span>Comentários sobre operações com tipos de dados distintos</a></span></li></ul></li><li><span><a href="#Funções-universais-da-NumPy" data-toc-modified-id="Funções-universais-da-NumPy-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Funções universais da NumPy</a></span></li><li><span><a href="#Alguns-métodos-de-numpy.ndarray-úteis" data-toc-modified-id="Alguns-métodos-de-numpy.ndarray-úteis-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Alguns métodos de <code>numpy.ndarray</code> úteis</a></span><ul class="toc-item"><li><span><a href="#Valores-máximos-e-mínimos-em-um-array" data-toc-modified-id="Valores-máximos-e-mínimos-em-um-array-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>Valores máximos e mínimos em um array</a></span></li><li><span><a href="#Somas-e-produtos-dos-valores-em-um-array" data-toc-modified-id="Somas-e-produtos-dos-valores-em-um-array-2.5.2"><span class="toc-item-num">2.5.2&nbsp;&nbsp;</span>Somas e produtos dos valores em um array</a></span></li><li><span><a href="#E-o-que-acontece-em-arrays-multidimensionais?" data-toc-modified-id="E-o-que-acontece-em-arrays-multidimensionais?-2.5.3"><span class="toc-item-num">2.5.3&nbsp;&nbsp;</span>E o que acontece em arrays multidimensionais?</a></span></li></ul></li><li><span><a href="#Indexação,-fatiamento-e-iterações-em-arrays" data-toc-modified-id="Indexação,-fatiamento-e-iterações-em-arrays-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Indexação, fatiamento e iterações em arrays</a></span></li></ul></li></ul></div>

## Pré-requisitos

Podemos explorar nossos estudos desse ponto em diante de duas formas:

* Localmente com Jupyter Notebooks;
* Remotamente com o [Google Colab](https://colab.research.google.com).

Este último já vem previamente configurado com todas as libs que utilizaremos na parte numérica do curso. Para a primeira opção, para que tudo corra bem, precisamos garantir que todo mundo está utilizando a mesma versão tanto do Python quanto em suas libs. Para isso, vamos utilizar o [conda](https://conda.io/en/latest/), um gerenciador open source de pacotes e ambientes.

### Instalação do conda (Miniconda)

Caso sua máquina não possua o conda instalado, você pode baixar o instalador condizente com seu computador e sistema operacional [neste link](https://conda.io/en/latest/miniconda.html), basta seguir as instruções lá providenciadas. Com isso, você instalará o Miniconda - a versão com "o mínimo necessário" do conda - em seu computador, que é o que iremos precisar aqui.

### Utilizando e instalando ambientes (envs)

Após instalado o `conda` e reiniciado seu terminal, você deve ser capaz de checar os ambientes (environments, que chamaremos apenas de envs) instalados (execute o comando abaixo sem `!` no seu terminal):

In [1]:
!conda env list

# conda environments:
#
base                     /home/volps/miniconda3
daml                     /home/volps/miniconda3/envs/daml
fenics16-1               /home/volps/miniconda3/envs/fenics16-1
fenics16-2               /home/volps/miniconda3/envs/fenics16-2
fenics17-1               /home/volps/miniconda3/envs/fenics17-1
fenics17-2               /home/volps/miniconda3/envs/fenics17-2
fenics18-1               /home/volps/miniconda3/envs/fenics18-1
sci                      /home/volps/miniconda3/envs/sci
sci_env               *  /home/volps/miniconda3/envs/sci_env



Este comando lista os envs instalados. Note que já temos um env que você provavelmente ainda não tem (a menos que vc esteja executando este notebook no Colab). Vamos resolver isso?

Para tanto, siga a sequência de passos abaixo:

1. Clone o repositório remoto do curso para sua máquina com o comando `git clone https://github.com/pedrosiracusa/curso_python_eamc.git` e entre no diretório com `cd curso_python_eamc`

2. Adicione o canal (`conda-forge`) que utilizaremos para baixar os pacotes corretos no conda: `conda config --add channels conda-forge`

3. Crie o mesmo pacote que temos - o `sci_env` - por meio do arquivo de dependências `sci_env.yml` com o seguinte comando: `conda env create -f sci_env.yml`

4. Aguarde a instala...zzzzZZZZZZZZZZZZZZZZzzZZZzz

5. Após a instalação, reinicie seu terminal e acesse o ambiente com o comando `source activate sci_env` (Linux) ou `conda activate sci_env` (Windows).

Pronto, com isso temos exatamente o mesmo ambiente, com as mesmas bibliotecas!

## A biblioteca NumPy

### O que é?

É um pacote fundamental para aplicações de computação científica em Python. Com ele, o desenvolvedor é capaz de:

* Montar objetos matriciais N-dimensionais e objetos derivados desses;
* Realizar operações eficientes de Álgebra Linear computacional;
* Operações básicas de Estatística;
* Utilizar geração de números pseudo-aleatórios;
* Operações vetorizadas;
* Integrar com códigos em C/C++ e Fortran;

E muito mais!

### Conceitos básicos

#### Importando o pacote

In [2]:
import numpy as np

#### Tipo básico: `numpy.ndarray`

O tipo básico da `numpy` é o `numpy.ndarray`, o quão chamaremos aqui frequentemente de "array".

##### Inicializando

Um simples vetor:

In [3]:
array1 = np.array([1., 2., 3.])

array1

array([1., 2., 3.])

Uma matriz:

In [4]:
matrix1 = np.array(
    [[1., 2., 3.],
     [4., 5., 6.],
     [7., 8., 9.]]
)

matrix1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Note que a matriz nada mais é que um array de arrays.

Ao longo do curso, veremos outras formas de inicializar arrays.

**Atenção!!!**

A entrada para a criação de arrays deve ser listas ou tuplas:

In [5]:
array_tuple = np.array((1, 2, 3))

array_tuple

array([1, 2, 3])

In [6]:
matrix_mixed = np.array(
    [(1, 2, 3),
    [4, 5, 6]]
)

matrix_mixed

array([[1, 2, 3],
       [4, 5, 6]])

##### Inicializando arrays preenchidos com zeros ou um

Em algumas situações, já são conhecidas as demandas e estruturas dos arrays que vão ser utilizados. Neste caso, o numpy oferece funções para criar arrays preenchidos com zeros ou um.

* Vetor

In [7]:
array_zeros = np.zeros(3)
array_zeros

array([0., 0., 0.])

* Matriz

In [62]:
shape = (4, 4)
matrix_zeros = np.zeros(shape)
matrix_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Analogamente, podemos fazer com valor unitário.

* Vetor

In [63]:
array_ones = np.ones(3)
array_ones

array([1., 1., 1.])

* Matriz

In [64]:
shape = (4, 4)
matrix_ones = np.ones(shape)
matrix_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##### Atributos básicos

* Número de eixos (axes) do array:

In [8]:
array1.ndim

1

In [9]:
matrix1.ndim

2

Note que uma matriz, nesse caso, é considerado um objeto bidimensional, já que são arrays dentro de um array.

* Forma de um array:

In [10]:
array1.shape

(3,)

In [11]:
matrix1.shape

(3, 3)

`ndarray.shape` fornece as dimensões de cada eixo. No caso de uma matriz $A \in \mathbb{R}^{m\,\times\,n}$, como temos em `matrix1`, `ndarray.shape` retorna justamente $(m, n)$.

* Tamanho de um array:

In [12]:
array1.size

3

In [13]:
matrix1.size

9

Retorna o número de entrada de valores no objeto `ndarray`.

* Tipo dos elementos em um array:

In [14]:
array1.dtype

dtype('float64')

In [15]:
matrix1.dtype

dtype('float64')

Ou seja, todas as entradas foram compostas por números em representação de ponto flutuante de dupla precisão. Caso seja necessário utilizar outro tipo de representação, podemos especificar isso na hora de declaramos o array por meio do argumento `dtype`:

In [16]:
matrix1_32 = np.array(
    [[1., 2., 3.],
     [4., 5., 6.],
     [7., 8., 9.]],
    dtype=np.float32
)

In [17]:
matrix1_32.dtype

dtype('float32')

Ou mesmo podemos criar arrays de números complexos:

In [18]:
array_complex = np.array([[2. + 3.j, 1.]], dtype=np.complex)

array_complex

array([[2.+3.j, 1.+0.j]])

In [19]:
matrix_complex = np.array(
    [[2. + 1.j, 1.],
     [0., 1.j]], 
    dtype=np.complex
)

matrix_complex

array([[2.+1.j, 1.+0.j],
       [0.+0.j, 0.+1.j]])

* Tamanhos dos itens em bytes de um array:

In [20]:
array1.itemsize

8

In [21]:
matrix1.itemsize

8

In [22]:
matrix1_32.itemsize

4

Note que um array de `float64` tem $\dfrac{64}{8} = 8$ bytes, enquanto um `float32` tem $\dfrac{32}{8} = 4$ bytes.

* Endereço dos dados em memória:

In [23]:
array1.data

In [24]:
matrix1.data

In [25]:
matrix1_32.data

Em Python, geralmente não utilizamos esse tipo de acesso ou informação. Utilizamos apenas a **_parte boa_** do C.

### Operações e utilitários básicos

#### Criação de arrays a partir de intervalos:

In [26]:
sequence_1 = np.arange(start=2, stop=10, step=2)

sequence_1

array([2, 4, 6, 8])

ou

In [27]:
sequence_2 = np.linspace(start=2, stop=8, num=4)

sequence_2

array([2., 4., 6., 8.])

Note que embora ambos criem arrays igualmente espaçados, exite uma diferença na forma de uso. O `np.arange` te possibilita dizer o início e o fim, sendo que o fim não está incluso (assim como ocorre com os _slicing_ de listas). Além disso, o `np.arange` controla o incremento que será utilizado até alcançar o fim da sequência.

Em contrapartida, o `np.linspace` controla precisamente o início e o fim (que estará incluso). No entanto, ele tem como entrada no terceiro argumento (aqui explicitado) a quantidade de pontos que terá entre o início e o fim. O incremento será consequência disso.

Para simplificar, geralmente ambos os métodos são usados com o nome dos argumentos implícitos:

In [28]:
sequence_1 = np.arange(2, 10, 2)

sequence_1

array([2, 4, 6, 8])

In [29]:
sequence_2 = np.linspace(2, 8, 4)

sequence_2

array([2., 4., 6., 8.])

In [30]:
sequence_3 = np.linspace(0, 100, 200)

sequence_3

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

#### Operações aritméticas

Com o numpy, as operações aritméticas são realizadas elemento-por-elemento do array.

In [31]:
a = np.arange(5)

a

array([0, 1, 2, 3, 4])

(note que se `np.arange` tiver apenas um argumento, ele gerará uma sequência igualmente espaçada até o número inteiro imediatamente antes ao argumento)

In [32]:
b = np.arange(0, 50, 10)

b

array([ 0, 10, 20, 30, 40])

In [33]:
soma = a + b
subtracao = b - a
potenciacao = a ** 2
divisao = b[1:] / a[1:]
produto = a * b

print(soma)
print(subtracao)
print(potenciacao)
print(divisao)
print(produto)

[ 0 11 22 33 44]
[ 0  9 18 27 36]
[ 0  1  4  9 16]
[10. 10. 10. 10.]
[  0  10  40  90 160]


Note que a operação de divisão de vetores não é matematicamente definida, mas aqui é possível pois se trata de operações elemento-por-elemento. Além disso, o produto entre vetores matematicamente definido como produto interno não ocorre por meio do operador `*` (iremos ver isso em breve). Podemos fazer com matrizes de maneira similar:

In [34]:
A = np.array(
    [[1., 3.], 
     [2., 4.]]
)
B = np.array(
    [[10., 0.], 
     [10., 20.]]
)

print(A, '\n')
print(B)

[[1. 3.]
 [2. 4.]] 

[[10.  0.]
 [10. 20.]]


In [35]:
soma = A + B
subtracao = B - A
potenciacao = A ** 2
divisao = B / A
produto = A * B

print(soma, '\n')
print(subtracao, '\n')
print(potenciacao, '\n')
print(divisao, '\n')
print(produto)

[[11.  3.]
 [12. 24.]] 

[[ 9. -3.]
 [ 8. 16.]] 

[[ 1.  9.]
 [ 4. 16.]] 

[[10.  0.]
 [ 5.  5.]] 

[[10.  0.]
 [20. 80.]]


Novamente, note que a operação de divisão em matrizes matematicamente não existe e o produto entre matrizes também não é o usual. As operações que ocorrem acima foram realizadas elemento-por-elemento. Caso desejemos realizar o produto de matrizes, o Python oferece um operador específico para isso:

In [36]:
produto_matrizes = A @ B

produto_matrizes

array([[40., 60.],
       [60., 80.]])

ou

In [37]:
produto_matrizes_alternativo = A.dot(B)

produto_matrizes_alternativo

array([[40., 60.],
       [60., 80.]])

sendo esse último uma notação mais verbosa do que está ocorrendo. Podemos, dessa forma, fazer a clássica operação entre matrizes e vetores do tipo $Ax$:

In [38]:
mat = np.array([[2., 1.], [1, 2.]])
vec = np.array([1., 0.])
prod_matvec = mat @ vec

prod_matvec

array([2., 1.])

#### Comentários sobre operações com tipos de dados distintos

Quando se opera objetos `ndarray` com tipos diferentes, o que será que acontece?

In [39]:
a = np.ones(3, dtype=np.int32)

a

array([1, 1, 1], dtype=int32)

In [40]:
b = np.linspace(0, 5, 3)

b

array([0. , 2.5, 5. ])

In [41]:
a + b

array([1. , 3.5, 6. ])

Note que ocorre uma coerção de tipo para o que apresentar maior grau de precisão (ou mais genérico).

### Funções universais da NumPy

A NumPy fornece as principais funções matemáticas capazes de operar de forma vetorial. Em outras palavras, capaz de retornar arrays, ao contrário da biblioteca-padrão `math`. Vamos ver um exemplo simples:

In [42]:
import math


def sin_function(x):
    return math.sin(x)

In [43]:
vec = np.array([1 / 3, 1 / 2])
sin_vec = sin_function(vec)

sin_vec

TypeError: only size-1 arrays can be converted to Python scalars

Pela numpy:

In [44]:
def sin_function_np(x):
    return np.sin(x)

In [45]:
sin_vec = sin_function_np(vec)

sin_vec

array([0.3271947 , 0.47942554])

Basicamente, as funções fornecidas são as mesmas que as da lib `math`, porém com a capacidade exibida acima. Lembrando que essas funções também são executadas elemento-por-elemento. A lista completa de funções disponíveis pode ser acessada [aqui](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html).

### Alguns métodos de `numpy.ndarray` úteis

No dia-a-dia científico, muitas vezes necessitamos de algumas operações com certa frequência, como somas em vetores, valores máximos ou mínimos e etc. Os objetos `ndarray` são munidos de métodos que executam esses cálculos. Vejamos alguns deles a seguir.

#### Valores máximos e mínimos em um array

Vamos antes gerar um vetor de valores aleatórios com o pacote `random` do numpy:

In [46]:
from numpy import random as rnd

array1 = rnd.random(10)

array1

array([0.7614099 , 0.71219846, 0.61883025, 0.76019822, 0.66769953,
       0.94367497, 0.26333924, 0.65633946, 0.08702671, 0.91648634])

Criamos um vetor com 10 entradas aleatórias entre 0 e 1. Agora vamos retirar algumas informações sobre ele.

* Valor máximo

In [47]:
array1.max()

0.9436749692146683

* Índice da entrada de valor máximo

In [48]:
imax = array1.argmax()
imax

5

In [49]:
array1[imax]

0.9436749692146683

* Valor mínimo

In [50]:
array1.min()

0.08702670518461131

* Índice da entrada de valor mínimo

In [51]:
array1.argmin()

8

#### Somas e produtos dos valores em um array

* Soma dos valores

In [52]:
array1.sum()

6.387203076934282

* Soma cumulativa

In [53]:
array1.cumsum()

array([0.7614099 , 1.47360836, 2.09243861, 2.85263683, 3.52033636,
       4.46401133, 4.72735057, 5.38369003, 5.47071673, 6.38720308])

Note que:

In [54]:
array1.sum() == array1.cumsum()[-1]

False

* Produto dos valores

In [55]:
array1.prod()

0.0022158689452186626

* Produto cumulativo dos valores

In [56]:
array1.cumprod()

array([0.7614099 , 0.54227496, 0.33557615, 0.25510439, 0.17033308,
       0.16073907, 0.0423289 , 0.02778213, 0.00241779, 0.00221587])

Também é constatado que:

In [57]:
array1.prod() == array1.cumprod()[-1]

True

#### E o que acontece em arrays multidimensionais?

Neste caso, o formato não é levado em conta. O método é aplicado ao longo do array como se os valores de entradas fossem uma lista.

In [58]:
shape = (3, 3)
vec1 = rnd.random(shape)

vec1

array([[0.06921396, 0.17257047, 0.57821624],
       [0.37884567, 0.06710757, 0.94436659],
       [0.3617863 , 0.02112304, 0.77601573]])

In [59]:
vec1.min()

0.021123035008924318

Porém, podemos especificar em qual `axis` os métodos serão aplicados:

In [60]:
vec1.min(axis=1)

array([0.06921396, 0.06710757, 0.02112304])

A operação acima retornou o mínimo de cada linha. Analogamente:

In [61]:
vec1.min(axis=0)

array([0.06921396, 0.02112304, 0.57821624])

retornou o mínimo em cada coluna. O procedimento pode ser aplicado da mesma maneira para as funções expostas anteriormente.

### Indexação, fatiamento e iterações em arrays

In [65]:
array1 = np.linspace(5, 20, 10)
array1

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ])

Semelhantemente às listas